ARG version
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /install

RUN apt-get -y update
RUN apt-get -y install curl
RUN apt-get -y install unzip

WORKDIR /source

# copy csproj and restore as distinct layers
COPY jenuine-worker/* ./jenuine-worker/
COPY jenuine-core/* ./jenuine-core/
COPY nap-genuine.sln .

RUN dotnet restore jenuine-worker/jenuine-worker.csproj
RUN dotnet publish jenuine-worker/jenuine-worker.csproj -c release -o /app --no-restore -p:PackageVersion=${version}

##### final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0

RUN apt-get -y update
RUN apt-get -y install curl

WORKDIR /app
COPY --from=build /app .
COPY run-worker.bash /app
COPY jenuine-worker/Properties/* /app/Properties/

RUN ls -lrt

EXPOSE 8080

ENTRYPOINT ["./run-worker.bash"]

# test demo
